services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports: 
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/src
    ports:
      - 3000:3000
    environment:
      - SUBWAY_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    privileged: true
    restart: "on-failure"