services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports: 
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/src
    ports:
      - 3000:3000
    environment:
      - SUBWAY_API_URL=http://backend:8000
      - GTFS_STOP_IDS=A45,S01
      - MIN_MINS=5
      - MAX_MINS=15
    depends_on:
      backend:
        condition: service_healthy
    privileged: true
    restart: "on-failure"
  backend-tests:
    build: 
      context: ./backend
      dockerfile: Dockerfile.tests
    volumes:
      - ./backend:/backend  # Mount the backend directory directly
    command: bash -c "poetry run coverage run -m pytest && poetry run coverage report --show-missing"