services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./backend:/app
    ports: 
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  backend-tests:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./backend:/backend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./frontend:/app/src
    ports:
      - 3000:3000
    environment:
      - SUBWAY_API_URL=http://backend:8000
      - GTFS_STOP_IDS=A45,A46,G33
      - MIN_MINS=5
      - MAX_MINS=20
    depends_on:
      backend:
        condition: service_healthy
    privileged: true
    restart: "on-failure"
  
  frontend-tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./frontend:/frontend