name: Run Tests on Pull Requests

on:
  pull_request:
    branches:
      - main  # Or any branch you'd like to target for pull requests
      - feat--multiple-stops

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.21
        options: >-
          --privileged
        ports:
          - 8000:8000  

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build and Run Backend Tests
      run: |
        docker compose build backend-tests
        docker compose run --rm backend-tests

    - name: Build and Run Frontend Tests
      run: |
        docker compose build frontend-tests
        docker compose run --rm frontend-tests

